### ISSUE TITLE
Cannot Find app.json

### ISSUE THREAD

**Issue by jmedran** [expo/turtle#203]
### New Issue Checklist

- [x] Updated turtle-cli to the latest version (`yarn global add turtle-cli` or `npm install --global turtle-cli`).
- [x] I read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I read [docs.expo.io](https://docs.expo.io) (Managed Workflow > Distributing Your App).
- [x] I searched for [existing GitHub issues](https://github.com/expo/turtle/issues).
- [x] **I enclosed the complete output when running turtle, including the stack trace and command used.**

### Issue Description

I am attempting to use Turtle in conjunction with Travis-CI to build a `.ipa` file. I am using the `.travis.yml` template provided in this project, with additional modifications relevant to my own build. I have updated the Travis-CI environment variables (as recommended in the doc) with the base64 encoded `.p12` file and `.mobileprovision` file. All of the setup commands in the job work as expected, however the build immediately fails when it reaches the `turtle build:ios` command with an error indicating an `app.json` file cannot be found despite it existing. Please see the "Build Standaline iOS" job below Travis-CI config below:

```
    - stage: Build Standalone iOS
      os: osx
      osx_image: xcode11.2
      language: node_js
      node_js: $NODE_VERSION
      env:
        - CACHE_NAME=build-ios-ipa YARN_CACHE_FOLDER="/Users/travis/yarn_cache"
      cache:
        directories:
          - $HOME/.turtle
          - $HOME/yarn_cache
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn global add turtle-cli@$TURTLE_VERSION
      script:
        - export ARTIFACT_PATH="/Users/travis/expo-project-$TRAVIS_COMMIT-`date +%s`.ipa"
        - turtle setup:ios --sdk-version $EXPO_SDK_VERSION || travis_terminate 1
        - echo $EXPO_IOS_DIST_P12_BASE64 > expo-project_dist.p12.base64
        - base64 --decode expo-project_dist.p12.base64 > expo-project_dist.p12
        - echo $EXPO_IOS_PROVISIONING_PROFILE_BASE64 > expo-project.mobileprovision.base64
        - base64 --decode expo-project.mobileprovision.base64 > expo-project.mobileprovision
        - turtle build:ios 
          --team-id $EXPO_APPLE_TEAM_ID 
          --dist-p12-path ./expo-project_dist.p12 
          --provisioning-profile-path ./expo-project.mobileprovision
          - o $ARTIFACT_PATH
      after_success:
        - echo $ARTIFACT_PATH
```

##### Command executed
`turtle build:ios --team-id $EXPO_APPLE_TEAM_ID --dist-p12-path ./expo-project_dist.p12 --provisioning-profile-path ./expo-project.mobileprovision`

##### Complete output when running turtle, including the stack trace and command used
```
$ git clone --depth=50 --branch=development https://github.com/jmedran/text-books.git jmedran/text-books
0.03s

jmedran/text-books

0.03s

Setting environment variables from repository settings

$ export EXPO_USERNAME=[secure]

$ export EXPO_PASSWORD=[secure]

$ export EXPO_APPLE_TEAM_ID=[secure]

$ export EXPO_IOS_DIST_P12_PASSWORD=[secure]

$ export EXPO_IOS_PROVISIONING_PROFILE_BASE64=[secure]

$ export EXPO_IOS_DIST_P12_BASE64=[secure]

Setting environment variables from .travis.yml

$ export EXPO_SDK_VERSION="36.0.0"

$ export TURTLE_VERSION="0.14.3"

$ export NODE_VERSION="12.13.1"

$ export YARN_VERSION="1.21.1"

$ export CACHE_NAME=build-ios-ipa

$ export YARN_CACHE_FOLDER="/Users/travis/yarn_cache"

nvm.install

4.91s$ nvm install $NODE_VERSION

cache.1

Setting up build cache

cache.npm

$ node --version

v12.13.1

$ npm --version

6.12.1

$ nvm --version

0.35.3

before_install.1

2.24s$ curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
before_install.2

0.01s$ export PATH="$HOME/.yarn/bin:$PATH"
install

83.10s$ yarn global add turtle-cli@$TURTLE_VERSION
before_script

11.18s$ npm install -g npm@latest

0.01s$ pwd

/Users/travis/build/jmedran/text-books

The command "pwd" exited with 0.

0.01s$ ls

App.js

README.md

__tests__

app.json

assets

babel.config.js

config.js

constants

index.js

navigation

package-lock.json

package.json

screens

src

The command "ls" exited with 0.

0.01s$ export ARTIFACT_PATH="/Users/travis/expo-project-$TRAVIS_COMMIT-`date +%s`.ipa"

The command "export ARTIFACT_PATH="/Users/travis/expo-project-$TRAVIS_COMMIT-`date +%s`.ipa"" exited with 0.

7.95s$ turtle setup:ios --sdk-version $EXPO_SDK_VERSION || travis_terminate 1

Apr 5 19:00:07 turtle[4992] INFO:  it's all set!

  platform: "ios"

  buildPhase: "setting up environment"

The command "turtle setup:ios --sdk-version $EXPO_SDK_VERSION || travis_terminate 1" exited with 0.

0.01s$ echo $EXPO_IOS_DIST_P12_BASE64 > expo-project_dist.p12.base64

The command "echo $EXPO_IOS_DIST_P12_BASE64 > expo-project_dist.p12.base64" exited with 0.

0.02s$ base64 --decode expo-project_dist.p12.base64 > expo-project_dist.p12

The command "base64 --decode expo-project_dist.p12.base64 > expo-project_dist.p12" exited with 0.

0.01s$ echo $EXPO_IOS_PROVISIONING_PROFILE_BASE64 > expo-project.mobileprovision.base64

The command "echo $EXPO_IOS_PROVISIONING_PROFILE_BASE64 > expo-project.mobileprovision.base64" exited with 0.

0.02s$ base64 --decode expo-project.mobileprovision.base64 > expo-project.mobileprovision

The command "base64 --decode expo-project.mobileprovision.base64 > expo-project.mobileprovision" exited with 0.

18.79s$ turtle build:ios --team-id $EXPO_APPLE_TEAM_ID --dist-p12-path ./expo-project_dist.p12 --provisioning-profile-path ./expo-project.mobileprovision - o $ARTIFACT_PATH

Apr 5 19:00:26 turtle[5029] ERROR: Failed to build standalone app

  err: Error: Couldn't find app.json.

      at Object.loadAppJSON (/Users/travis/.config/yarn/global/node_modules/turtle-cli/src/bin/utils/project.ts:14:11)

      at /Users/travis/.config/yarn/global/node_modules/turtle-cli/src/bin/utils/builder.ts:75:23

      at Command.<anonymous> (/Users/travis/.config/yarn/global/node_modules/turtle-cli/src/bin/index.ts:23:12)

  platform: "ios"

The command "turtle build:ios --team-id $EXPO_APPLE_TEAM_ID --dist-p12-path ./expo-project_dist.p12 --provisioning-profile-path ./expo-project.mobileprovision - o $ARTIFACT_PATH" exited with 1.

store build cache

0.01sKchanges detected (content changed, file is created, or file is deleted):\n/Users/travis/.npm/_cacache/index-v5/af/03/5c781820370e585dc2323edbbc80669bf714da5b47d56510c7d0bd7521ee

/Users/travis/.npm/anonymous-cli-metrics.json

/Users/travis/yarn_cache/v6/npm-p-limit-2.3.0-3dd33c647a214fdfffd835933eb086da0dc21db1-integrity/node_modules/p-limit/.yarn-metadata.json

/Users/travis/yarn_cache/v6/npm-p-limit-2.3.0-3dd33c647a214fdfffd835933eb086da0dc21db1-integrity/node_modules/p-limit/.yarn-tarball.tgz

/Users/travis/yarn_cache/v6/npm-p-limit-2.3.0-3dd33c647a214fdfffd835933eb086da0dc21db1-integrity/node_modules/p-limit/index.d.ts

/Users/travis/yarn_cache/v6/npm-p-limit-2.3.0-3dd33c647a214fdfffd835933eb086da0dc21db1-integrity/node_modules/p-limit/index.js

/Users/travis/yarn_cache/v6/npm-p-limit-2.3.0-3dd33c647a214fdfffd835933eb086da0dc21db1-integrity/node_modules/p-limit/license

/Users/travis/yarn_cache/v6/npm-p-limit-2.3.0-3dd33c647a214fdfffd835933eb086da0dc21db1-integrity/node_modules/p-limit/package.json

/Users/travis/yarn_cache/v6/npm-p-limit-2.3.0-3dd33c647a214fdff\n...

changes detected, packing new archive
store build cache

Done. Your build exited with 1.
```

### Environment

<details>
  <pre> [  Expo CLI 3.16.1 environment info:

    System:

      OS: macOS Mojave 10.14.6

      Shell: 3.2.57 - /bin/bash

    Binaries:

      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node

      Yarn: 1.21.1 - ~/.yarn/bin/yarn

      npm: 6.14.4 - ~/.nvm/versions/node/v12.13.1/bin/npm

    IDEs:

      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild

    npmPackages:

      expo: ~36.0.0 => 36.0.2 

      react: ~16.9.0 => 16.9.0 

      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 

      react-navigation: ~3.0.9 => 3.0.9 ] </pre>
</details>

Thanks in advance for any clarification that can be provided. Expo is an unbelievable tool and the community appreciates it! Let me know if there is any other information that may be of help.
