### ISSUE TITLE
IPA build is not working

### ISSUE THREAD

**Issue by tobiasbenkner** [expo/turtle#282]
Hi,

I followed this guide https://www.robincussol.com/build-standalone-expo-apk-ipa-with-turtle-cli/ to build the ipa file. The build was successful. Then I uploaded the ipa file to the App Store. Installed TestFlight to install the App on my IPhone. When I open the App following error occur.

**Error**
```
Could not connect to development server
...
URL: http://127.0.0.1:8000/bundles/ios-8beb0c...9b.js
```

<img src="https://raw.githubusercontent.com/tobiasbenkner/random/master/app.jpg" width=300 />

**Build Environment**
- Azure Agent MACOS 10.15 https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
- XCODE 12.2
- Fastlane 2.168.0
- turtle-cli@0.20.0
- expo-cli@4.0.8
- turtle setup:ios --sdk-version 39.0.3

**build-ios.sh**
```shell script
#!/bin/bash
[ -z "${EXPO_IOS_DIST_P12_PASSWORD}" ] && echo "EXPO_IOS_DIST_P12_PASSWORD is unset" && exit 1;
[ -z "${APPLE_TEAM_ID}" ] && echo "APPLE_TEAM_ID is unset" && exit 1;
[ -z "${BUILD_NUMBER}" ] && echo "BUILD_NUMBER is unset" && exit 1;

printf "\n\nInstall imagemagick\n"
brew install imagemagick

printf "\n\nInstall Expo\n"
npm install -g expo-cli || exit 1;

printf "\n\nInstall turtle-cli\n"
npm install -g turtle-cli || exit 1;

printf "\n\nInstall yarn install\n"
yarn install

printf "\n\nSetup SDK\n"
turtle setup:ios --sdk-version 39.0.3

printf "\n\nRemove Alpha Channel and replace transparency with white\n"
find assets -name "*.png" -exec convert "{}" -background white -alpha remove -alpha off "{}" \;

printf "\n\nUpdate buildNumber\n"
jq ".expo.ios.buildNumber = \"$BUILD_NUMBER\"" app.json > app.new.json && \
  mv app.new.json app.json

printf "\n\nBuild Expo\n"
rm -rf dist
expo export --dev --public-url http://127.0.0.1:8000

printf "\n\nStart Webserver for dist\n"
cd dist || exit 1;
python3 -m http.server &
cd ..

printf "\n\nBuild iOS\n"
turtle build:ios \
  --team-id "${APPLE_TEAM_ID}" \
  --dist-p12-path ios_distribution.p12 \
  --provisioning-profile-path example_Test.mobileprovision \
  --allow-non-https-public-url \
  --public-url http://127.0.0.1:8000/ios-index.json \
  -o app.ipa
```

**Build-Log**
- https://gist.github.com/tobiasbenkner/7a4711a5e0abc846df0c0f1c6ce9ab85

**What should I do?**

Is this behavior normal? Should I provide every build version on a public server? It feels wrong to keep all versions public. On the Android build I don't need to do it.

Thank you for your help!!

Greets,
Tobias

**Comment by jpcodr** [comment]
Hello @tobiasbenkner i have the same issue. Actually, i wrote on the expo forums ([Standalone iOS app builded with turtle-cli fails](https://forums.expo.io/t/standalone-ios-app-builded-with-turtle-cli-fails/46673))


Did you found any solution?

**Comment by tobiasbenkner** [comment]
¡Hola! @jpcodr 

I could **not** find a solution that works for IOS on the local computer for testing purpose.

For the production I would definitely choose a server that provides the sources publicly. Just for the reason of the updates. They will come over the air instead of the App store or Play store. Your updates will be available directly  and you don't have to wait for a review from apple or google.

**Free solution for https public**
You can use Github or Gitlab Pages for Expo bundles.

**Artifactory**
You can host e.g. Artifactory and get ssl certificates with Let's Encrypt. Inside of Artifactory you can create a public repository where you store your Expo Bundles. The benifit is that you can just upload, download and deletes files via a web ui.

```
version: '3'

volumes:
  artifactory_home:
  artifactory_db:

services:

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:7.4.3
    restart: always
    volumes:
      - artifactory_home:/var/opt/jfrog/artifactory
      - /etc/localtime:/etc/localtime:ro
      - /backup:/backup:ro
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    environment:
      - JF_SHARED_DATABASE_TYPE=postgresql
      - JF_SHARED_DATABASE_USERNAME=user
      - JF_SHARED_DATABASE_PASSWORD=secret
      - JF_SHARED_DATABASE_URL=jdbc:postgresql://artifactory_postgres:5432/artifactory
      - JF_SHARED_DATABASE_DRIVER=org.postgresql.Driver
    depends_on:
      - artifactory_postgres

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.artifactory.rule=Host(`artifactory.domain.tld`) && PathPrefix(`/`)"
      - "traefik.http.routers.artifactory.tls=true"
      - "traefik.http.routers.artifactory.tls.certresolver=le"
      - "traefik.http.services.artifactory.loadbalancer.server.port=8082"

  artifactory_postgres:
    image: postgres:9.6.11
    environment:
      - POSTGRES_DB=artifactory
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    volumes:
      - artifactory_db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
```

**NGINX**
You can also start a Nginx Server and host your bundles there. it's light weighted but no gui. For the certificates I would also use Let's encrypt.

**local https server**
this solution can also work locally but I didn't tried it out. https://www.npmjs.com/package/https-localhost maybe this can work out for locally testing and debugging.

**Solution**
For production I would use Gitlab or Github Pages. There are to 99,9% available and free. You don't need to take care of updates, security issues, and so on.

For local debugging I would try the **local https server**. Maybe it works out of the box. In my point of view it's very complicated in the beginning to understand the certificates workflow. You need to generate your own generated self signed certificates and you need trust them that you will get a valid connection to your https server.

I hope I could help!

¡Saludos!
