### ISSUE TITLE
Build standalone android app failed [SOLVED]

### ISSUE THREAD

**Issue by belizar** [expo/turtle#40]
Hello,

I am trying to integrate my app in Azure Deevops continuous integration pipeline and cannot build the app.

The build failed in last step.

my azuredevops.yaml file is:
```
# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'


steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sudo add-apt-repository ppa:webupd8team/java 
              && sudo apt-get update 
              && echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
              && echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections 
              && sudo apt-get --assume-yes install oracle-java8-installer'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
    # Download and cache dependencies
- script: npm install
  displayName: 'Install Dependencies'

  # install expo cli
- script: npm install -g gulp-cli
  displayName: 'Install Gulp'

- script: npm install  --unsafe-perm -g turtle-cli
  displayName: 'Install Turtle '

- script: export EXPO_ANDROID_KEYSTORE_PASSWORD=$(Keystore_password) 
          && export EXPO_ANDROID_KEY_PASSWORD=$(Key_password)
  displayName: 'Set android keystore environment variables'

- script: turtle setup:android 
  displayName: 'Setup android environment'
  
- script: turtle ba -u $(user_expo) -p $(pwd_expo) --keystore-alias $(Key_alias) --keystore-path ../keys/TrekkoReactNative.jks -o ~/trekko.apk
  displayName: 'Build apk'
```
And the error is:

![image](https://user-images.githubusercontent.com/37871475/55961767-f84ff800-5c45-11e9-8418-4de77ba55973.png)

Thanks in advance
