### ISSUE TITLE
Issue running `turtle setup:android` on 0.8.1

### ISSUE THREAD

**Issue by awinograd** [expo/turtle#87]
Not sure if this is related to the issues in #85 and #86 as there's not a ton of detail...

I'm running a circleci build with the following config:

```
jobs:                                                                                                                 
  build:                                                                                                              
    resource_class: xlarge                                                                                            
    docker:                                                                                                           
      # https://github.com/expo/expo-turtle-android                                                                   
      - image: dsokal/expo-turtle-android                                                                             
    working_directory: ~/apps-canvas                                                                                  
    environment:                                                                                                      
      TURTLE_VERSION: 0.8.1                                                                                           
      PLATFORM: android                                                                                               
      YARN_CACHE_FOLDER: ~/yarn_cache                                                                                 
      EXPO_SDK_VERSION: 33.0.0   
...
      - run:                                                                                                          
          name: Setting up environment for Turtle                                                                     
          command: turtle setup:$PLATFORM --sdk-version $EXPO_SDK_VERSION
```

Looks like the `dsokal/expo-turtle-android` image may need to include `rsync`?

Here's truncated output from my circleci build:

```
Jun 10 18:17:49 turtle[203] INFO:  $ expo-yarn-workspaces check-workspace-dependencies && rm -rf node_modules/babel-jest/node_modules/babel-core
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Jun 10 18:17:49 turtle[203] INFO:  ✅  Verified that all workspace dependencies are symlinked.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Jun 10 18:17:49 turtle[203] INFO:  $ yarn workspace expo prepare
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Jun 10 18:17:50 turtle[203] INFO:  yarn workspace v1.9.4
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Jun 10 18:17:50 turtle[203] INFO:  yarn run v1.9.4
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Jun 10 18:17:50 turtle[203] INFO:  $ expo-module prepare && npm run generate-lazy
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Jun 10 18:17:50 turtle[203] INFO:  Tried to guess the docs homepage for expo; add it under the "homepage" entry in package.json
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Jun 10 18:17:50 turtle[203] INFO:  expo-module-scripts: README.md exists, not updating
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Jun 10 18:17:50 turtle[203] INFO:  /home/circleci/.turtle/workingdir/android/sdk33/packages/expo-module-scripts/bin/expo-module-configure: line 14: rsync: command not found
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Jun 10 18:17:50 turtle[203] INFO:  error Command failed with exit code 127.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Jun 10 18:17:50 turtle[203] INFO:  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Jun 10 18:17:50 turtle[203] INFO:  error Command failed.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Jun 10 18:17:50 turtle[203] INFO:  Exit code: 1
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Jun 10 18:17:50 turtle[203] INFO:  Command: /usr/local/bin/node
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Jun 10 18:17:50 turtle[203] INFO:  Arguments: /opt/yarn-v1.9.4/lib/cli.js prepare
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Jun 10 18:17:50 turtle[203] INFO:  Directory: /home/circleci/.turtle/workingdir/android/sdk33/packages/expo
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Jun 10 18:17:50 turtle[203] INFO:  Output:
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Jun 10 18:17:50 turtle[203] INFO:  info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Jun 10 18:17:50 turtle[203] INFO:  error Command failed with exit code 1.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stderr"
Jun 10 18:17:50 turtle[203] INFO:  info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
  platform: "android"
  buildPhase: "setting up environment"
  source: "stdout"
Jun 10 18:17:50 turtle[203] ERROR: Failed to setup environment for android builds
  err: Error: yarn exited with non-zero code: 1
      at ChildProcess.completionListener (/home/circleci/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:317:30)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:915:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
      ...
      at spawnAsync (/home/circleci/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at Object.<anonymous> (/@expo/xdl@54.1.4/src/detach/ExponentTools.js:127:21)
      at Generator.next (<anonymous>)
      at step (/home/circleci/.config/yarn/global/node_modules/@expo/xdl/build/detach/ExponentTools.js:261:191)
      at /home/circleci/.config/yarn/global/node_modules/@expo/xdl/build/detach/ExponentTools.js:261:437
      at new Promise (<anonymous>)
      at Object.<anonymous> (/home/circleci/.config/yarn/global/node_modules/@expo/xdl/build/detach/ExponentTools.js:261:99)
      at Object.spawnAsyncThrowError (/home/circleci/.config/yarn/global/node_modules/@expo/xdl/build/detach/ExponentTools.js:89:18)
      at _installNodeModules (/home/circleci/.config/yarn/global/node_modules/turtle-cli/src/bin/setup/android/index.ts:93:23)
      at <anonymous>
  platform: "android"
Exited with code 1
```
